spring:
  cloud:
    gateway:
      routes:
        - id: fooding-api
          uri: ${FOODING_API_URI}
          predicates:
            - Path=/v1/**
          filters:
            - StripPrefix=1
        - id: fooding-realtime
          uri: ${FOODING_REALTIME_URI}
          predicates:
            - Path=/v2/**, /v3/**

server:
  port: ${SERVER_PORT:8080}
