name: REALTIME STAGE

on:
  push:
    branches: [develop]
    paths:
      - 'fooding-realtime/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - '.github/workflows/realtime-develop.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.BUILD_SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :fooding-realtime:bootJar
      - name: DBuild Realtime
        uses: docker/build-push-action@v3
        with:
          context: .
          file: fooding-realtime/Dockerfile
          push: true
          tags: hyperrealitycorp/fooding-realtime-api-stage
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            SPRING_PROFILES_ACTIVE=${{ secrets.STAGE_SPRING_PROFILES_ACTIVE }}
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGE_REMOTE_SSH_IP }}
          username: ${{ secrets.STAGE_REMOTE_SSH_ID }}
          password: ${{ secrets.STAGE_REMOTE_SSH_PASSWORD }}
          port: ${{ secrets.STAGE_REMOTE_SSH_PORT }}
          script: |
            source ~/.bashrc
            bash ./deployment/fooding/realtime-api-stage.sh
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: "#build-status"
        if: always()
